### ISSUE TITLE
Update for GHC 7.10

### ISSUE THREAD

**Issue by crockeea** [rrnewton/intel-aes#9]
Is this package still maintained? It doesn't build with GHC 7.10.

**Comment by rrnewton** [comment]
I'm afraid it hasn't been for a while.  I didn't know anyone was using it.  If you are, we could try to reboot it.

**Comment by crockeea** [comment]
I was considering using it after reading [this article](http://tommd.github.io/posts/RNG-Bench.html), but if it's not being maintained, then that's one less choice to consider!

**Comment by rrnewton** [comment]
Well, ping us back one more time to let us know if "crypto-api w/RDRAND", which wins that benchmark, successfully handles.  From that article it sounds like the only potential problem with the RDRAND approach is reproducibility...

In principal it should not be hard to get intel-aes or something like intel-aes working again.  It's just a bundling of Intel's sample code for using the aes instruction.
